import os
import re

# --- CHANGE WORKING DIRECTORY TO SCRIPT LOCATION ---
os.chdir(os.path.dirname(os.path.abspath(__file__)))
# ---------------------------------------------------

def update_top_pkg():
    # Configuration
    output_filename = "top_pkg.svh"
    current_dir = os.getcwd()
    
    found_packages = []

    print(f"Working in: {current_dir}")

    # 1. Iterate over all files in the current directory
    for filename in os.listdir(current_dir):
        # We process only SystemVerilog files containing '_pkg'
        if filename.endswith(".sv") and "_pkg" in filename:
            
            try:
                with open(filename, 'r', encoding='utf-8') as f:
                    content = f.read()
                    
                    # 2. Regex to find the actual 'package <name>;' declaration
                    # This is safer than relying on the filename
                    match = re.search(r'^\s*package\s+(\w+)\s*;', content, re.MULTILINE)
                    
                    if match:
                        pkg_name = match.group(1)
                        found_packages.append(pkg_name)
                        print(f"  [+] Found package '{pkg_name}' in {filename}")
                    else:
                        print(f"  [-] Skipped {filename}: No 'package' declaration found.")
            except Exception as e:
                print(f"  [!] Error reading {filename}: {e}")

    # Sort packages alphabetically for clean output
    found_packages.sort()

    # 3. Write the top_pkg.svh file
    try:
        with open(output_filename, 'w', encoding='utf-8') as f:
            f.write("// ============================================================\n")
            f.write(f"// AUTOMATICALLY GENERATED FILE -- DO NOT EDIT MANUALLY\n")
            f.write(f"// Generated by script in: {current_dir}\n")
            f.write("// ============================================================\n\n")
            
            if not found_packages:
                f.write("// No packages found in this directory.\n")
            else:
                for pkg in found_packages:
                    f.write(f"import {pkg}::*;\n")
            
            f.write("\n// End of imports\n")
            
        print(f"\nSUCCESS: '{output_filename}' has been updated with {len(found_packages)} imports.")
        
    except Exception as e:
        print(f"\nERROR: Could not write to {output_filename}: {e}")

if __name__ == "__main__":
    update_top_pkg()