// ============================================================
// AUTOMATICALLY GENERATED FILE -- DO NOT EDIT MANUALLY
// Generated by script in: c:\VerilogRTLCourse\lab9\design\packages
// ============================================================

import common_pkg::*;
import defs_pkg::*;
import display_defs_pkg::*;
import fifo_defs_pkg::*;
import pixel_mem_pkg::*;
import regs_pkg::*;
import seq_defs_pkg::*;
import uart_defs_pkg::*;

// End of imports
